import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_Components/Header"; // Corrected filename

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:px-10">
          <Header/>{children} {/* Corrected component name */}
        </div>
      </body>
    </html>
  );
}
