
import "./globals.css";
import Header from "./_Components/Header";
import Footer from "./_Components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="md:px-20">
          <Header/>{children}
        </div>
        <Footer/> 
      </body>
    </html>
  );
}

